--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/9/2018 7:34:18 p. m.
-- Server version: 5.5.5-10.1.35-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE restaurant;

--
-- Drop table `receta`
--
DROP TABLE IF EXISTS receta;

--
-- Drop table `insumo`
--
DROP TABLE IF EXISTS insumo;

--
-- Drop table `menudia`
--
DROP TABLE IF EXISTS menudia;

--
-- Drop table `platoespecial`
--
DROP TABLE IF EXISTS platoespecial;

--
-- Drop table `detalleventa`
--
DROP TABLE IF EXISTS detalleventa;

--
-- Drop table `menu`
--
DROP TABLE IF EXISTS menu;

--
-- Drop table `plato`
--
DROP TABLE IF EXISTS plato;

--
-- Drop table `cuenta`
--
DROP TABLE IF EXISTS cuenta;

--
-- Drop table `cliente`
--
DROP TABLE IF EXISTS cliente;

--
-- Drop table `mesero`
--
DROP TABLE IF EXISTS mesero;

--
-- Drop table `mesa`
--
DROP TABLE IF EXISTS mesa;

--
-- Set default database
--
USE restaurant;

--
-- Create table `mesa`
--
CREATE TABLE mesa (
  CodigoMesa int(11) NOT NULL AUTO_INCREMENT,
  Cuenta int(11) NOT NULL,
  PRIMARY KEY (CodigoMesa)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `mesero`
--
CREATE TABLE mesero (
  CodigoMesero int(11) NOT NULL AUTO_INCREMENT,
  CodigoMesa int(11) NOT NULL,
  PRIMARY KEY (CodigoMesero)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE mesero
ADD CONSTRAINT FK_mesero_mesa_CodigoMesa FOREIGN KEY (CodigoMesa)
REFERENCES mesa (CodigoMesa) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  NitCliente int(11) NOT NULL,
  CantidadPlatos int(11) NOT NULL,
  CodigoPlato int(11) DEFAULT NULL,
  CodigoPlatoEspecial int(11) DEFAULT NULL,
  NombreNit varchar(255) NOT NULL,
  PRIMARY KEY (NitCliente)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `cuenta`
--
CREATE TABLE cuenta (
  NitCliente int(11) NOT NULL,
  PrecioPlato int(11) NOT NULL,
  CantidadPlatos int(11) NOT NULL,
  NombrePlato varchar(255) NOT NULL,
  codigoMesa int(11) NOT NULL,
  PRIMARY KEY (NitCliente)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `UK_cuenta_CantidadPlatos` on table `cuenta`
--
ALTER TABLE cuenta
ADD UNIQUE INDEX UK_cuenta_CantidadPlatos (CantidadPlatos);

--
-- Create foreign key
--
ALTER TABLE cuenta
ADD CONSTRAINT FK_cuenta_cliente_NitCliente FOREIGN KEY (NitCliente)
REFERENCES cliente (NitCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE cuenta
ADD CONSTRAINT FK_cuenta_mesa_CodigoMesa FOREIGN KEY (codigoMesa)
REFERENCES mesa (CodigoMesa) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `plato`
--
CREATE TABLE plato (
  CodigoPlato int(11) NOT NULL AUTO_INCREMENT,
  NombrePlato varchar(255) NOT NULL,
  PrecioPlato double NOT NULL,
  TamañoPlato varchar(255) DEFAULT NULL,
  PRIMARY KEY (CodigoPlato)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `menu`
--
CREATE TABLE menu (
  CodigoMenu int(11) NOT NULL AUTO_INCREMENT,
  CodigoPlato int(11) NOT NULL,
  NombrePlato varchar(255) NOT NULL,
  PRIMARY KEY (CodigoMenu)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE menu
ADD CONSTRAINT FK_menu_plato_CodigoPlato FOREIGN KEY (CodigoPlato)
REFERENCES plato (CodigoPlato) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `detalleventa`
--
CREATE TABLE detalleventa (
  CodigoPlato int(11) NOT NULL,
  CantidadPlato int(11) NOT NULL,
  codigoPlatoEspecial int(11) NOT NULL,
  PRIMARY KEY (CodigoPlato)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_cuenta_CantidadPlatos FOREIGN KEY (CodigoPlato)
REFERENCES cuenta (CantidadPlatos) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_plato_CodigoPlato FOREIGN KEY (CodigoPlato)
REFERENCES plato (CodigoPlato) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `platoespecial`
--
CREATE TABLE platoespecial (
  CodigoPlatoEspecial int(11) NOT NULL,
  NombrePlato varchar(255) NOT NULL,
  PrecioPlato double NOT NULL,
  PRIMARY KEY (CodigoPlatoEspecial)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE platoespecial
ADD CONSTRAINT FK_platoespecial_detalleventa_CodigoPlato FOREIGN KEY (CodigoPlatoEspecial)
REFERENCES detalleventa (CodigoPlato) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `menudia`
--
CREATE TABLE menudia (
  CodigoMenuEspecial int(11) NOT NULL,
  Fecha int(11) NOT NULL,
  CodigoPlatoEspecial int(11) NOT NULL,
  PRIMARY KEY (CodigoMenuEspecial)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE menudia
ADD CONSTRAINT FK_menudia_platoespecial_CodigoPlatoEspecial FOREIGN KEY (CodigoPlatoEspecial)
REFERENCES platoespecial (CodigoPlatoEspecial) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `insumo`
--
CREATE TABLE insumo (
  CodigoInsumo int(11) NOT NULL AUTO_INCREMENT,
  CantidadInsumo int(11) NOT NULL,
  NombreInsumo varchar(255) NOT NULL,
  PRIMARY KEY (CodigoInsumo)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `receta`
--
CREATE TABLE receta (
  CodigoPlato int(11) NOT NULL,
  CodigoInsumo int(11) NOT NULL,
  CantidadInsumo int(11) NOT NULL,
  PRIMARY KEY (CodigoPlato)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE receta
ADD CONSTRAINT FK_receta_insumo_CodigoInsumo FOREIGN KEY (CodigoInsumo)
REFERENCES insumo (CodigoInsumo) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE receta
ADD CONSTRAINT FK_receta_plato_CodigoPlato FOREIGN KEY (CodigoPlato)
REFERENCES plato (CodigoPlato) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table mesa
--
-- Table restaurant.mesa does not contain any data (it is empty)

-- 
-- Dumping data for table cliente
--
-- Table restaurant.cliente does not contain any data (it is empty)

-- 
-- Dumping data for table plato
--
-- Table restaurant.plato does not contain any data (it is empty)

-- 
-- Dumping data for table cuenta
--
-- Table restaurant.cuenta does not contain any data (it is empty)

-- 
-- Dumping data for table detalleventa
--
-- Table restaurant.detalleventa does not contain any data (it is empty)

-- 
-- Dumping data for table insumo
--
-- Table restaurant.insumo does not contain any data (it is empty)

-- 
-- Dumping data for table platoespecial
--
-- Table restaurant.platoespecial does not contain any data (it is empty)

-- 
-- Dumping data for table receta
--
-- Table restaurant.receta does not contain any data (it is empty)

-- 
-- Dumping data for table mesero
--
-- Table restaurant.mesero does not contain any data (it is empty)

-- 
-- Dumping data for table menudia
--
-- Table restaurant.menudia does not contain any data (it is empty)

-- 
-- Dumping data for table menu
--
-- Table restaurant.menu does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;